plugins {
    id 'java-library'
}

java {
    sourceCompatibility = '25'
    targetCompatibility = '25'
}

dependencies {
    api project(':wallet-core')
    implementation libs.jackson.databind
    implementation libs.slf4j.api

    testImplementation libs.junit.jupiter.api
    testRuntimeOnly libs.junit.jupiter.engine
    testRuntimeOnly libs.junit.platform.launcher
    testImplementation libs.assertj.core
}

test {
    useJUnitPlatform()
}
